### ISSUE TITLE
manual installation fails

### ISSUE THREAD

**Issue by christinazavou** [krrish94/chamferdist#13]
Hello, 

I have a conda environment with torch1.6 and cudatoolkit 10.2.89
However on my machine nvcc --version shows V10.1.243

When i have this environment activate and clone the repository and run python setup.py install I get the following error.

```
running install
running bdist_egg
running egg_info
creating chamferdist.egg-info
writing chamferdist.egg-info/PKG-INFO
writing dependency_links to chamferdist.egg-info/dependency_links.txt
writing requirements to chamferdist.egg-info/requires.txt
writing top-level names to chamferdist.egg-info/top_level.txt
writing manifest file 'chamferdist.egg-info/SOURCES.txt'
reading manifest file 'chamferdist.egg-info/SOURCES.txt'
writing manifest file 'chamferdist.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
creating build
creating build/lib.linux-x86_64-3.7
creating build/lib.linux-x86_64-3.7/chamferdist
copying chamferdist/chamfer.py -> build/lib.linux-x86_64-3.7/chamferdist
copying chamferdist/version.py -> build/lib.linux-x86_64-3.7/chamferdist
copying chamferdist/__init__.py -> build/lib.linux-x86_64-3.7/chamferdist
copying chamferdist/knn.cu -> build/lib.linux-x86_64-3.7/chamferdist
copying chamferdist/dispatch.cuh -> build/lib.linux-x86_64-3.7/chamferdist
copying chamferdist/index_utils.cuh -> build/lib.linux-x86_64-3.7/chamferdist
copying chamferdist/mink.cuh -> build/lib.linux-x86_64-3.7/chamferdist
copying chamferdist/cutils.h -> build/lib.linux-x86_64-3.7/chamferdist
copying chamferdist/knn.h -> build/lib.linux-x86_64-3.7/chamferdist
running build_ext
building 'chamferdist._C' extension
creating /media/christina/Data/coding/chamferdist/build/temp.linux-x86_64-3.7
creating /media/christina/Data/coding/chamferdist/build/temp.linux-x86_64-3.7/chamferdist
Emitting ninja build file /media/christina/Data/coding/chamferdist/build/temp.linux-x86_64-3.7/build.ninja...
Compiling objects...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
[1/3] /usr/bin/nvcc -DWITH_CUDA -Ichamferdist -I/home/christina/miniconda3/envs/py3-mink/lib/python3.7/site-packages/torch/include -I/home/christina/miniconda3/envs/py3-mink/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -I/home/christina/miniconda3/envs/py3-mink/lib/python3.7/site-packages/torch/include/TH -I/home/christina/miniconda3/envs/py3-mink/lib/python3.7/site-packages/torch/include/THC -I/home/christina/miniconda3/envs/py3-mink/include/python3.7m -c -c /media/christina/Data/coding/chamferdist/chamferdist/knn.cu -o /media/christina/Data/coding/chamferdist/build/temp.linux-x86_64-3.7/chamferdist/knn.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -DCUDA_HAS_FP16=1 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=_C -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_61,code=sm_61 -std=c++14
FAILED: /media/christina/Data/coding/chamferdist/build/temp.linux-x86_64-3.7/chamferdist/knn.o 
/usr/bin/nvcc -DWITH_CUDA -Ichamferdist -I/home/christina/miniconda3/envs/py3-mink/lib/python3.7/site-packages/torch/include -I/home/christina/miniconda3/envs/py3-mink/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -I/home/christina/miniconda3/envs/py3-mink/lib/python3.7/site-packages/torch/include/TH -I/home/christina/miniconda3/envs/py3-mink/lib/python3.7/site-packages/torch/include/THC -I/home/christina/miniconda3/envs/py3-mink/include/python3.7m -c -c /media/christina/Data/coding/chamferdist/chamferdist/knn.cu -o /media/christina/Data/coding/chamferdist/build/temp.linux-x86_64-3.7/chamferdist/knn.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -DCUDA_HAS_FP16=1 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=_C -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_61,code=sm_61 -std=c++14
/usr/include/c++/8/utility(307): error: pack expansion does not make use of any argument packs

/usr/include/c++/8/utility(329): error: pack expansion does not make use of any argument packs

/usr/include/c++/8/utility(329): error: expected a ">"
          detected during instantiation of type "std::make_integer_sequence<std::size_t, _Num>" 
(340): here

/usr/include/c++/8/utility(307): error: identifier "__integer_pack" is undefined
          detected during:
            instantiation of class "std::_Build_index_tuple<_Num> [with _Num=1UL]" 
/usr/include/c++/8/functional(389): here
            instantiation of class "std::_Bind<_Functor (_Bound_args...)> [with _Functor=lambda [](std::function<c10::IValue ()>)->void, _Bound_args=<std::function<c10::IValue ()>>]" 
/home/christina/miniconda3/envs/py3-mink/lib/python3.7/site-packages/torch/include/ATen/core/ivalue_inl.h(361): here

/usr/include/c++/8/utility(307): error: expected a ">"
          detected during:
            instantiation of class "std::_Build_index_tuple<_Num> [with _Num=1UL]" 
/usr/include/c++/8/functional(389): here
            instantiation of class "std::_Bind<_Functor (_Bound_args...)> [with _Functor=lambda [](std::function<c10::IValue ()>)->void, _Bound_args=<std::function<c10::IValue ()>>]" 
/home/christina/miniconda3/envs/py3-mink/lib/python3.7/site-packages/torch/include/ATen/core/ivalue_inl.h(361): here

/usr/include/c++/8/functional(482): error: no instance of function template "std::_Bind<_Functor (_Bound_args...)>::__call [with _Functor=lambda [](std::function<c10::IValue ()>)->void, _Bound_args=<std::function<c10::IValue ()>>]" matches the argument list
            argument types are: (std::tuple<>, <error-type>)
            object type is: std::_Bind<lambda [](std::function<c10::IValue ()>)->void (std::function<c10::IValue ()>)>
          detected during:
            instantiation of "_Result std::_Bind<_Functor (_Bound_args...)>::operator()(_Args &&...) [with _Functor=lambda [](std::function<c10::IValue ()>)->void, _Bound_args=<std::function<c10::IValue ()>>, _Args=<>, _Result=void]" 
/usr/include/c++/8/bits/std_function.h(298): here
            instantiation of "void std::_Function_handler<void (_ArgTypes...), _Functor>::_M_invoke(const std::_Any_data &, _ArgTypes &&...) [with _Functor=std::_Bind<lambda [](std::function<c10::IValue ()>)->void (std::function<c10::IValue ()>)>, _ArgTypes=<>]" 
/usr/include/c++/8/bits/std_function.h(675): here
            instantiation of "std::function<_Res (_ArgTypes...)>::function(_Functor) [with _Res=void, _ArgTypes=<>, _Functor=std::_Bind<lambda [](std::function<c10::IValue ()>)->void (std::function<c10::IValue ()>)>, <unnamed>=void, <unnamed>=void]" 
/home/christina/miniconda3/envs/py3-mink/lib/python3.7/site-packages/torch/include/ATen/core/ivalue_inl.h(353): here

6 errors detected in the compilation of "/tmp/tmpxft_0001519b_00000000-6_knn.cpp1.ii".
[2/3] c++ -MMD -MF /media/christina/Data/coding/chamferdist/build/temp.linux-x86_64-3.7/chamferdist/knn_cpu.o.d -pthread -B /opt/anaconda1anaconda2anaconda3/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DWITH_CUDA -Ichamferdist -I/home/christina/miniconda3/envs/py3-mink/lib/python3.7/site-packages/torch/include -I/home/christina/miniconda3/envs/py3-mink/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -I/home/christina/miniconda3/envs/py3-mink/lib/python3.7/site-packages/torch/include/TH -I/home/christina/miniconda3/envs/py3-mink/lib/python3.7/site-packages/torch/include/THC -I/home/christina/miniconda3/envs/py3-mink/include/python3.7m -c -c /media/christina/Data/coding/chamferdist/chamferdist/knn_cpu.cpp -o /media/christina/Data/coding/chamferdist/build/temp.linux-x86_64-3.7/chamferdist/knn_cpu.o -std=c++14 -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=_C -D_GLIBCXX_USE_CXX11_ABI=0
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
In file included from /home/christina/miniconda3/envs/py3-mink/lib/python3.7/site-packages/torch/include/ATen/Parallel.h:149:0,
                 from /home/christina/miniconda3/envs/py3-mink/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/utils.h:3,
                 from /home/christina/miniconda3/envs/py3-mink/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/nn/cloneable.h:5,
                 from /home/christina/miniconda3/envs/py3-mink/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/nn.h:3,
                 from /home/christina/miniconda3/envs/py3-mink/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/all.h:7,
                 from /home/christina/miniconda3/envs/py3-mink/lib/python3.7/site-packages/torch/include/torch/extension.h:4,
                 from /media/christina/Data/coding/chamferdist/chamferdist/knn_cpu.cpp:3:
/home/christina/miniconda3/envs/py3-mink/lib/python3.7/site-packages/torch/include/ATen/ParallelOpenMP.h:84:0: warning: ignoring #pragma omp parallel [-Wunknown-pragmas]
 #pragma omp parallel for if ((end - begin) >= grain_size)
 
[3/3] c++ -MMD -MF /media/christina/Data/coding/chamferdist/build/temp.linux-x86_64-3.7/chamferdist/ext.o.d -pthread -B /opt/anaconda1anaconda2anaconda3/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DWITH_CUDA -Ichamferdist -I/home/christina/miniconda3/envs/py3-mink/lib/python3.7/site-packages/torch/include -I/home/christina/miniconda3/envs/py3-mink/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -I/home/christina/miniconda3/envs/py3-mink/lib/python3.7/site-packages/torch/include/TH -I/home/christina/miniconda3/envs/py3-mink/lib/python3.7/site-packages/torch/include/THC -I/home/christina/miniconda3/envs/py3-mink/include/python3.7m -c -c /media/christina/Data/coding/chamferdist/chamferdist/ext.cpp -o /media/christina/Data/coding/chamferdist/build/temp.linux-x86_64-3.7/chamferdist/ext.o -std=c++14 -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=_C -D_GLIBCXX_USE_CXX11_ABI=0
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
In file included from /home/christina/miniconda3/envs/py3-mink/lib/python3.7/site-packages/torch/include/ATen/Parallel.h:149:0,
                 from /home/christina/miniconda3/envs/py3-mink/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/utils.h:3,
                 from /home/christina/miniconda3/envs/py3-mink/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/nn/cloneable.h:5,
                 from /home/christina/miniconda3/envs/py3-mink/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/nn.h:3,
                 from /home/christina/miniconda3/envs/py3-mink/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/all.h:7,
                 from /home/christina/miniconda3/envs/py3-mink/lib/python3.7/site-packages/torch/include/torch/extension.h:4,
                 from /media/christina/Data/coding/chamferdist/chamferdist/ext.cpp:1:
/home/christina/miniconda3/envs/py3-mink/lib/python3.7/site-packages/torch/include/ATen/ParallelOpenMP.h:84:0: warning: ignoring #pragma omp parallel [-Wunknown-pragmas]
 #pragma omp parallel for if ((end - begin) >= grain_size)
 
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "/home/christina/miniconda3/envs/py3-mink/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1515, in _run_ninja_build
    env=env)
  File "/home/christina/miniconda3/envs/py3-mink/lib/python3.7/subprocess.py", line 512, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "setup.py", line 88, in <module>
    cmdclass={"build_ext": BuildExtension},
  File "/home/christina/miniconda3/envs/py3-mink/lib/python3.7/site-packages/setuptools/__init__.py", line 163, in setup
    return distutils.core.setup(**attrs)
  File "/home/christina/miniconda3/envs/py3-mink/lib/python3.7/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/home/christina/miniconda3/envs/py3-mink/lib/python3.7/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/home/christina/miniconda3/envs/py3-mink/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/christina/miniconda3/envs/py3-mink/lib/python3.7/site-packages/setuptools/command/install.py", line 67, in run
    self.do_egg_install()
  File "/home/christina/miniconda3/envs/py3-mink/lib/python3.7/site-packages/setuptools/command/install.py", line 109, in do_egg_install
    self.run_command('bdist_egg')
  File "/home/christina/miniconda3/envs/py3-mink/lib/python3.7/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/christina/miniconda3/envs/py3-mink/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/christina/miniconda3/envs/py3-mink/lib/python3.7/site-packages/setuptools/command/bdist_egg.py", line 175, in run
    cmd = self.call_command('install_lib', warn_dir=0)
  File "/home/christina/miniconda3/envs/py3-mink/lib/python3.7/site-packages/setuptools/command/bdist_egg.py", line 161, in call_command
    self.run_command(cmdname)
  File "/home/christina/miniconda3/envs/py3-mink/lib/python3.7/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/christina/miniconda3/envs/py3-mink/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/christina/miniconda3/envs/py3-mink/lib/python3.7/site-packages/setuptools/command/install_lib.py", line 11, in run
    self.build()
  File "/home/christina/miniconda3/envs/py3-mink/lib/python3.7/distutils/command/install_lib.py", line 107, in build
    self.run_command('build_ext')
  File "/home/christina/miniconda3/envs/py3-mink/lib/python3.7/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/christina/miniconda3/envs/py3-mink/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/christina/miniconda3/envs/py3-mink/lib/python3.7/site-packages/setuptools/command/build_ext.py", line 87, in run
    _build_ext.run(self)
  File "/home/christina/miniconda3/envs/py3-mink/lib/python3.7/distutils/command/build_ext.py", line 340, in run
    self.build_extensions()
  File "/home/christina/miniconda3/envs/py3-mink/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 649, in build_extensions
    build_ext.build_extensions(self)
  File "/home/christina/miniconda3/envs/py3-mink/lib/python3.7/distutils/command/build_ext.py", line 449, in build_extensions
    self._build_extensions_serial()
  File "/home/christina/miniconda3/envs/py3-mink/lib/python3.7/distutils/command/build_ext.py", line 474, in _build_extensions_serial
    self.build_extension(ext)
  File "/home/christina/miniconda3/envs/py3-mink/lib/python3.7/site-packages/setuptools/command/build_ext.py", line 208, in build_extension
    _build_ext.build_extension(self, ext)
  File "/home/christina/miniconda3/envs/py3-mink/lib/python3.7/distutils/command/build_ext.py", line 534, in build_extension
    depends=ext.depends)
  File "/home/christina/miniconda3/envs/py3-mink/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 478, in unix_wrap_ninja_compile
    with_cuda=with_cuda)
  File "/home/christina/miniconda3/envs/py3-mink/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1233, in _write_ninja_file_and_compile_objects
    error_prefix='Error compiling objects for extension')
  File "/home/christina/miniconda3/envs/py3-mink/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1529, in _run_ninja_build
    raise RuntimeError(message)
RuntimeError: Error compiling objects for extension

```

Do you have any hint of what the issue is?

Thanks

**Comment by adizhol** [comment]
+1
pytorch 1.7.1 cuda 11.1

**Comment by zou-longkun** [comment]
I have met the same issue. pytorch 1.9.1 cuda 11.1
